# src/metrics.py
"""Performance metrics and Monte Carlo significance test."""

from __future__ import annotations

import numpy as np
import pandas as pd


def sharpe_ratio(returns: pd.Series, annualization: int = 252) -> float:
    """Annualized Sharpe ratio (risk-free rate = 0).

    For a series with effectively-zero variance but non-zero mean
    (e.g. all returns identical), the denominator is set to abs(mean)
    so that a constant-return strategy has Sharpe = sqrt(annualization).
    """
    mean = returns.mean()
    std = returns.std()
    if np.isnan(std):
        return 0.0
    # Treat near-machine-precision zero std as degenerate constant series
    if std == 0 or (abs(mean) > 0 and std < abs(mean) * 1e-10):
        if mean == 0:
            return 0.0
        std = abs(mean)
    return float(mean / std * np.sqrt(annualization))


def sortino_ratio(returns: pd.Series, annualization: int = 252) -> float:
    """Annualized Sortino ratio (penalises only downside volatility)."""
    downside = returns[returns < 0]
    if len(downside) == 0 or downside.std() == 0:
        return float("inf") if returns.mean() > 0 else 0.0
    return float(returns.mean() / downside.std() * np.sqrt(annualization))


def max_drawdown(equity_curve: pd.Series) -> float:
    """Maximum peak-to-trough drawdown as a positive fraction (0-1)."""
    roll_max = equity_curve.cummax()
    drawdown = (equity_curve - roll_max) / roll_max
    return float(abs(drawdown.min()))


def monte_carlo_test(
    strategy_returns: pd.Series,
    n_simulations: int = 1000,
    seed: int = 42,
) -> dict:
    """Sign-randomization test: is the strategy Sharpe significantly positive?

    The null hypothesis is that the strategy has no edge, i.e. its returns are
    symmetric around zero (a profitable day is no more likely than an equally
    sized losing day).  Under that null each return's sign is equally likely to
    be + or -, so the null distribution of the Sharpe ratio is generated by
    randomly flipping the sign of every return ``n_simulations`` times and
    recomputing the Sharpe each time.

    A plain permutation (shuffle without replacement) is deliberately NOT used:
    permuting returns leaves the mean and standard deviation unchanged, so
    every permuted Sharpe equals the observed Sharpe and the "null" collapses
    to a single constant value (which also makes a histogram of it impossible
    to bin).  Sign randomization preserves the magnitude distribution of the
    returns while destroying any directional edge, yielding a genuine,
    non-degenerate Monte-Carlo null centred on zero.

    p-value = fraction of sign-flipped Sharpes >= the observed Sharpe, i.e. how
    often pure noise with no directional edge reproduces a result at least as
    good as the strategy's.

    Returns
    -------
    dict with keys: observed_sharpe, null_sharpes, p_value, null_mean, null_std
    """
    rng = np.random.default_rng(seed)
    observed = sharpe_ratio(strategy_returns)
    rets_array = np.asarray(strategy_returns.values, dtype=float)
    n = len(rets_array)

    null_sharpes = np.array(
        [
            sharpe_ratio(pd.Series(rets_array * rng.choice([-1.0, 1.0], size=n)))
            for _ in range(n_simulations)
        ]
    )

    p_value = float(np.mean(null_sharpes >= observed))

    return {
        "observed_sharpe": observed,
        "null_sharpes": null_sharpes,
        "p_value": p_value,
        "null_mean": float(null_sharpes.mean()),
        "null_std": float(null_sharpes.std()),
    }
